"""add-isntallers

Revision ID: 8e7642982343
Revises: b02ff6f0d4a6
Create Date: 2025-05-25 13:08:22.847293

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8e7642982343'
down_revision: str | None = 'b02ff6f0d4a6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'installers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('version', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('creator_id', sa.UUID(), nullable=False),
        sa.Column('file_path', sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_installers_creator_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_installers')),
        sa.UniqueConstraint('version', name=op.f('uq_installers_version')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('installers')
    # ### end Alembic commands ###
