"""add-news

Revision ID: f4ae321d7aaa
Revises: 24b1fc46aaa1
Create Date: 2025-04-27 20:00:15.424616

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ae321d7aaa'
down_revision: str | None = '24b1fc46aaa1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'news',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('creator_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_news_creator_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_news')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
