class EmailPolicyViolationException(Exception): ...


class PasswordPolicyViolationException(Exception): ...


class NamePolicyViolationException(Exception): ...


class SessionDoesNotExistException(Exception): ...


class ExpiredSessionException(Exception): ...


class SessionAlreadyExistsException(Exception): ...


class PasswordMismatchException(Exception): ...
